services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - webnet

  api:
    build:
      context: ../../
      dockerfile: database_versioning/examples/api/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet:
    driver: bridge
